#! /bin/bash

export SXHKD_SHELL=bash
xrdb -merge  ~/.Xresources                                                                                                                                               
PATH=$PATH:~/bin

sxhkd -r ~/tmp/sxhkd.log -m 1 &

setxkbmap -layout eu &
xmodmap ~/.Xmodmap & 
xsetroot -cursor_name left_ptr &
xset m 1/1 0 & # Mouse acc
xset b off &

xset s 300 5 &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# CONFIGS
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding 27
bspc config bottom_padding	0
bspc config left_padding	 0
bspc config right_padding	 0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any
bspc config active_border_color "#2f2f2f"
bspc config normal_border_color "#2f2f2f"
bspc config focused_border_color "#cf6a4c"
bspc config focus_follows_pointer false

# RULES
bspc rule -a firefox desktop=web
bspc rule -a Chromium desktop=web
bspc rule -a jetbrains-pycharm desktop=code
bspc rule -a Slack desktop=chat
bspc rule -a Termite:ncmpcpp desktop=music 
bspc rule -a Termite:startterm desktop=term
bspc rule -a wificonfig sticky=on state=floating border=off
bspc rule -a paconfig sticky=on state=floating border=off
bspc rule -a scratchpad sticky=on state=floating border=off
bspc rule -a com-osbuddy-loader-Loader state=pseudo_tiled

feh --bg-fill --recursive /home/nickolaj/Pictures/ee.png 

# SETUP DISPLAYS
polybar top &
polybar external1 &
polybar external2 &

bspc monitor HDMI1 -d web code term music chat
bspc monitor HDMI2 -d mon2-1 mon2-2
bspc monitor VGA1 -d mon3-1 mon3-2

bspc wm --adopt-orphans

# SETUP APPS
dunst &
nm-applet &
slack &
chromium &
pycharm-professional &
