aur-packages := "uwsm"
wayland-packages := "ly pipewire wireplumber"
hyprland-packages := "hyprland hyprpaper hyprpolkitagent xdg-desktop-portal-hyprland"

_install-packages:
    sudo pacman -S --noconfirm --needed {{wayland-packages}} {{hyprland-packages}}
    yay -S --noconfirm --needed {{aur-packages}}

setup: _install-packages
    stow -t ~/.config .config
    cp ./hyprpaper.service $HOME/.config/systemd/user/hyprpaper.service
    systemctl --user enable hyprpaper.service
    systemctl --user enable hyprpolkitagent.service
    sudo systemctl enable ly.service
